# Generated by Django 5.0.3 on 2024-03-10 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                (
                    "company_status",
                    models.CharField(
                        choices=[
                            ("HIRING", "Hiring"),
                            ("HIRING_FREEZE", "Hiring Freeze"),
                            ("LAYOFFS", "Layoffs"),
                        ],
                        default="HIRING_FREEZE",
                        max_length=30,
                    ),
                ),
                (
                    "last_update",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("application_link", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True, max_length=100)),
            ],
        ),
    ]
